name: my-dork

services:
  postgres:
    image: postgres:15 #postgres:latest
    container_name: postgres_container_compose_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - /home/l/drogon_dev/drogon-auth/migrations:/docker-entrypoint-initdb.d/
      - /data/usershare/PG/pgdata-drogon-auth:/var/lib/postgresql/data
      #- pgdata:/var/lib/postgresql/data
      #- ./migrations:/docker-entrypoint-initdb.d/

#volumes:
#  pgdata: